### ISSUE TITLE
Bug Report - Github Issues Template

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#202]
Should include the following template to assist with bug reporting 

```yml

name: Bug Report 🐛
description: Submit a bug report to help us improve the library.
labels: [bug, discussion]
body:
  - type: markdown
    attributes: 
      value: |
        ## Thank you for taking the time to create a Bug Report!

        By submitting this bug report, you are actively contributing to the community. We'll work hard to get you back on track. Before you continue, we ask that you kindly review the pre-bug report checklist.

        ### Pre-Bug Report Checklist
        - I've reviewed the documentation and examples
        - I've tried uninstalling and reinstalling `node_modules`, (`package-lock.json`, `yarn-lock.json`, `pnpm-lock.yml`)
        - I've reviewed existing [Bug Reports](https://github.com/9mbs/calendar-widgets/labels/bug) and have verified my issue is new

        ### Please include as many of the following details in your bug report as possible
        - `calendar-widgets` version number in your project
        -  Screenshot of error(s)
        - What platforms are you seeing this error on? (e.g. desktop, mobile, native, etc)
        - If using a browser, what browsers are you seeing this error on? (Please list all)
        - Do you have a way for us to recreate your environment? (e.g a public repo we can clone and test?)
        - Please list any additional details in your report that might help us narrow down the root cause of the issue you're experiencing.

 
```
