### ISSUE TITLE
Add GitHub Action for Linting, Building, and Testing

### ISSUE THREAD

**Issue by 9mbs** [9mbs/calendar-widgets#92]
Create a GitHub Action that performs the following tasks:

1. Runs linters in the `./workspaces/calendar-widgets` directory using the command `pnpm run lint`
2. Builds the code in the `./workspaces/calendar-widgets` directory using the command `pnpm run build`
3. Runs the test suites in the `./workspaces/tests` directory using the command `pnpm run test`

This action will ensure that the code in the calendar-widgets workspace is properly linted, built, and tested before being deployed.

**Comment by 9mbs** [comment]
This was tricky for alot of reasons. We had the usual troubles with working with Mono repos, this required updated the root `package.json` to utilize the `workspaces` property. So we now "officially" are using workspaces. 

Another issue I encountered was needing to use a specific node version instead of the default version, pnpm requires atleast v16 

More fun, the `workspaces/tests` directory won't place nice with the Github Action environment because it's installing `calendar-widgets` via relative pathing. To resolve this we had to install around that directory.

```yml
- name: Install dependencies
        run: pnpm install --recursive --filter '.../!tests'
```

The next step was to run the following scripts in the `workspaces/calendar-workspaces` directory: `pnpm run build` and `pnpm run lint`. What's interesting is when I went to test the ESLint action, it was running successfully and passing the build... when it shouldn't be 🙄 I had intentionally set some errors that were failing on my local but they weren't catching in the build. This was the action:

```yml
# ...

- name: Install dependencies
        run: pnpm install --recursive --filter '.../!tests'

# ...

- name: Lint calendar-widgets
        working-directory: ./workspaces/calendar-widgets
        run: pnpx eslint --debug './src/**/*.{ts,tsx}' -c .eslintrc.cjs
```

Turns out, ESLint needed to be installed independently in the dependencies 🤷 

```yml
- name: Install dependencies
     run: |
          pnpm install --recursive --filter '.../!tests'
          cd workspaces/calendar-widgets
          pnpm install --save-dev eslint
```
